function(systeminfo)
    message("System ${CMAKE_SYSTEM}   Version ${CMAKE_SYSTEM_VERSION}   Processor ${CMAKE_SYSTEM_PROCESSOR}   Name ${CMAKE_SYSTEM_NAME}" )
endfunction()

function(checkipo)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT ipo_supported)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION False)
    if(ipo_supported)
        set(CMAKE_INTERPROCEDURAL_OPTIMIZATION True)
    endif()
     message("CMAKE_INTERPROCEDURAL_OPTIMIZATION=${CMAKE_INTERPROCEDURAL_OPTIMIZATION}" )
endfunction()

function(Format target directory)
    find_program(CLANG-FORMAT_PATH clang-format REQUIRED)
    set(EXPRESSION h hpp hh c cc cxx cpp)
    list(TRANSFORM EXPRESSION PREPEND "${directory}/*.")
    file(GLOB_RECURSE SOURCE_FILES FOLLOW_SYMLINKS LIST_DIRECTORIES false ${EXPRESSION})
    add_custom_command(TARGET ${target} PRE_BUILD COMMAND ${CLANG-FORMAT_PATH} -i --verbose --style=file ${SOURCE_FILES})
endfunction()